# Generated by Django 3.2.4 on 2021-06-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.ImageField(upload_to='resume'),
        ),
    ]
