# Generated by Django 3.2.4 on 2021-06-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
