# Generated by Django 3.2.4 on 2021-07-03 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210703_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='resume_dl',
        ),
    ]
